name: open-dev-journey-provider

networks:
  open-dev-blog-nw:
    driver: bridge
    name: open-dev-blog-nw

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - open-dev-blog-nw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker/docker_data/mongodb_data:/data/db

  postgres:
    image: postgres:16
    container_name: postgresdb
    restart: unless-stopped
    networks:
      - open-dev-blog-nw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/docker_data/postgres_data:/var/lib/postgresql/data
      - ./docker/init/init-postgres-db.sql:/docker-entrypoint-initdb.d/init-db.sql
